Hide already used (non-`multiple`) options
click-contrib/click-repl pull request #104
Opened 2023-06-21 15:27 UTC by ZanyMonk

Change only applied for options with `multiple=False`.

### Before
```sh
> cmd <TAB>
                      --foo
                      --bar
> cmd --foo t <TAB>
                      --foo
                      --bar
```

### After
```sh
> cmd <TAB>
                      --foo
                      --bar
> cmd --foo t <TAB>
                      --bar
```

2023-06-22 02:56 UTC, auvipy requested changes
please check the test failures

2023-06-22 06:52 UTC, GhostOps77 commented
This is made just to replicate the behaviour of the click's parsing style
if you've already supplied the values for the foo like `-foo t`, and if u supply it again like `-foo R`
then, foo's value will be overwritten

This is actually the intended way of behaviour

2023-06-22 07:02 UTC, ZanyMonk commented
@auvipy please check your CI.

@GhostOps77 this PR does not disallow one to use an option multiple times, it just hides the ones already used from the completions, which makes it much more practical in my opinion (you don't have to sort through all the options you already added to the command.

I can make it optional if you prefer. If not, just remove the PR :)

2023-06-22 07:12 UTC, GhostOps77 commented
@ZanyMonk It's a linter error, format the code before commiting
also, it would be better to have it as a flag to the completer class (via prompt kwargs) to decide whether to show already used non-multiple options or not

2023-06-23 20:06 UTC, ZanyMonk commented
Made it optional and fixed the format to fit flake8 test.

2023-07-11 07:18 UTC, auvipy approved these changes

2023-07-11 07:18 UTC, merged