Add a `shortest_only` option
click-contrib/click-repl pull request #105
Opened 2023-06-21 16:13 UTC by ZanyMonk

The `ClickCompleter` can now receive a `shortest_only` keyword argument.

If set to `True`, only the shortest version of each option will be shown by default (ie. if we keep pressing `Tab` & `Space`).

### Before
```sh
> cmd <TAB>
            --verbose
            -v
> cmd -<TAB>
            --verbose
            -v
```

### After
```sh
> cmd <TAB>
            -v
> cmd -<TAB>
            --verbose
            -v
```

2023-06-23 20:06 UTC, ZanyMonk commented
Fixed the format to fit flake8 test.

2023-07-11 07:20 UTC, auvipy requested changes
can you please rebase?

2023-07-13 06:00 UTC, auvipy commented
@GhostOps77

2023-07-15 06:46 UTC, GhostOps77 commented
@auvipy yep, this one looks good too!
and works very well.
You can merge this PR without any issues.

2023-07-15 09:16 UTC, auvipy approved these changes

2023-07-15 09:22 UTC, merged