Merged #68 : Added click's autocompletion support
click-contrib/click-repl pull request #88
Opened 2023-02-06 07:31 UTC by GhostOps77

Added the click's autocompletion support for click v7 and v8

Also added some test cases for it
And I've also segregated the test cases into separate file
I've moved all the main code to utils.py, and imported only the essential parts from the code explicitly, that the user's gonna use

Solves: #69 

And It also merges all my final changes in my main click-repl repository

After merging this PR, you can close these issues/PR

- #68
- #69 

- #64
- #65

- #74
- #80

2023-02-06 08:19 UTC, auvipy reviewed
can we check if we can consider this package for test?
https://pypi.org/project/pytest-click/

2023-02-06 13:25 UTC, GhostOps77 commented
> can we check if we can consider this package for test? https://pypi.org/project/pytest-click/

You can check it whether it can be used for tests or not

But it will still test only the click commands, but not the click_repl package as far as I've seen from their docs

2023-02-06 15:47 UTC, auvipy requested changes

2023-02-06 15:47 UTC, auvipy commented on README.md
> -[![Tests](https://github.com/GhostOps77/click-repl/actions/workflows/tests.yml/badge.svg?branch=GhostOps77-patch-1)](https://github.com/GhostOps77/click-repl/actions/runs/4074019555/jobs/7018648133)
why referencing your repo instead of main repo?

2023-02-06 16:26 UTC, GhostOps77 commented
@auvipy  Changed it, check it out

And also, I don't know what to do with the build badge, cuz there's no purpose in having it as we've remove the travis ci configs

But it's up to u now

2023-02-07 04:36 UTC, GhostOps77 commented
And I think this PR can be closed as well

#82

2023-02-07 09:53 UTC, auvipy approved these changes

2023-02-07 09:53 UTC, merged

2023-02-07 09:56 UTC, GhostOps77 commented
@auvipy hey, are u able to do the test using pytest-click?